name: Automated tests
on: [push]
jobs:
    build:
        env:
            GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GH_API_TOKEN }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: https://npm.pkg.github.com/
            - name: Install NPM dependencies
              run: npm ci
            - name: Launch formatting, linting and tests checks
              run: npm test
              env:
                  CI: true
