name: Deploy Integration

on:
    push:
        branches:
            - main

jobs:
    build:
        env:
            GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.GH_API_TOKEN }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  persist-credentials: false
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: https://npm.pkg.github.com/
            - name: Install NPM dependencies
              run: npm ci
            - name: Launch formatting, linting and tests checks
              run: VITE_ENV=integration npx env-cmd -f ./environments/.integration.env npm run build
              env:
                  CI: true
            - name: AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_CI_USER_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_CI_USER_SECRET_ACCESS_KEY }}
                  aws-region: eu-west-1
            - name: Run script file
              run: |
                  aws s3 sync ./build s3://weavit-web-app-integration --delete --cache-control max-age=31536000
            - name: Copy files to S3
              run: |
                  aws s3 cp s3://weavit-web-app-integration s3://weavit-web-app-integration --recursive --exclude "*" --include "*.html" --metadata-directive REPLACE --cache-control max-age:no-cache --content-type text/html
            - name: Invalid cache
              run: |
                  aws cloudfront create-invalidation --distribution-id=E1G8HLEUV6TXPS --paths "/*"
